config/routes.rb
Rails.application.routes.draw do
  resources :bots do
    collection { post :how }
  end
  resources :bot_users
  resources :pdfs
  resources :pages
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :sellers
  resources :materials
  root 'pages#about'
  resources :products
  get "products/:seller/:id", to: 'products#show', as: 'show_product'
  namespace 'api' do
    namespace 'v1' do
      resources :bot_users
  	end
  end

  get 'pages/about', to: 'pages#about'
  get 'pages/how', to: 'pages#how'

  get 'callback/index'
  post '/' => 'callback#received_data'
  get 'callback/received_data'
end

app/models/seller.rb
class Seller < ApplicationRecord
    mount_uploader :logo, LogoUploader
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]
	def should_generate_new_friendly_id?
	  name_changed?
	end
  has_many :products, dependent: :destroy
  belongs_to :user
  paginates_per 12
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_user! , only: [:create, :edit, :update, :destroy]
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  before_action :check_seller_owner, only:[:edit, :update]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all.order(:created_at).page(params[:page])
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @products = @seller.products.order(:created_at).page(params[:page])
    @seller = Seller.all
    respond_to do |format|
      format.html
      format.pdf do
        seller = SellerPdf.new(@seller)
        send_data seller.render, filename: "pdf_#{@seller.name}.seller",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /sellers/new
  def new
    if current_user
      @seller = Seller.new
    else
      redirect_to sellers_path
    end
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name, :products, :description, :materials, :logo_cache, :country, :website, :email, :logo, :material_name, :user_id)
    end

    def check_seller_owner
      if current_user.seller != @seller
        flash[:notice] = "You are not an authorized user to edit this store"
        redirect_to sellers_path
      end
    end

end

app/views/sellers/_form.html.erb
<div class="container" id="seller-form">
  <div class="image"></div>
  <div class="frm"><br />
      <div class="sub-title">APPLY TO SELL ON NANODEX</div><br />
        <%= form_for @seller, html: { multipart: true } do |form| %>
          <% if seller.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

              <ul>
              <% seller.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.text_field :name, placeholder: "Name", class: 'form-control', :required => true %>
          </div>

          <br />

          <div class="field">
            <%= form.text_area :description, placeholder: "Description (max 370 characters)", :maxlength => 370, class: 'form-control sell' %>
          </div>
          <br />

          <div class="field">
            <%= form.label :country_of_your_production_facility %>
            <%= form.country_select :country, priority_countries: ["US", "GB", "DE", "CN", "JP"], placeholder: "Country", class: 'form-control' %>
          </div>

          <br />

          <div class="input-group">
            <span class="input-group-addon" id="basic-addon3" aria-describedby="basic-addon3">Include "https://"</span>
            <%= form.text_field :website, placeholder: "https://yourwebsite.com", class: 'form-control' %>
          </div>

          <br />

          <div class="field">
            <%= form.text_field :email, placeholder: "Email", class: 'form-control'  %>
          </div>
          <br />
          <%= form.hidden_field :user_id,:value=>current_user.id %>
          <br />

          <div class="input-group">
            <%= form.label :logo_300x300px %><br />
            <%= form.file_field :logo %>
            <%= form.hidden_field :logo_cache %>
          </div>

          <br />

          <div class="actions">
            <%= form.submit "Become a seller", class: 'btn btn-primary' %>
          </div>
          <br />
        <% end %>
      </form>
  </div>
</div>

app/views/sellers/_random_seller.html.erb
<div class="sub-title">OTHER SELLERS</div>
<div class="thumbnail">
  <% if @random_seller %>
    <% if @random_seller.logo? %>
      <%= link_to (image_tag @random_seller.logo.url(:sidebar)), seller_path(@random_seller), class: 'seller-preview' %>
    <% else %>
      <%= link_to (image_tag '/thumbnail.png'), seller_path(@random_seller), class: 'seller-preview' %>
    <% end %>
    <div class="caption">
      <h4 style="font-size:16px;"><%= link_to @random_seller.name, seller_path(@random_seller) %></h4>
      <div style="font-size:12px;"><%= @random_seller.country %></div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <%#div class="col-xs-8 col-sm-6">
          <% &#9889; rating %>
        <%#/div>
        <%#div class="col-xs-4 col-sm-6"%>
        <center><%= link_to "Visit", @random_seller, class: 'white-text' %></center>
        <%#/div%>
      </div>                  
    </div>
  <% end %>
</div>
<div class="thumbnail">
  <% if @random_seller2 %>
    <% if @random_seller2.logo? %>
      <%= link_to (image_tag @random_seller2.logo.url(:sidebar)), seller_path(@random_seller2), class: 'seller-preview' %>
    <% else %>
      <%= link_to (image_tag '/thumbnail.png'), seller_path(@random_seller2), class: 'seller-preview' %>
    <% end %>
    <div class="caption">
      <h4 style="font-size:16px;"><%= link_to @random_seller2.name, seller_path(@random_seller2) %></h4>
      <div style="font-size:12px;"><%= @random_seller2.country %></div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <%#div class="col-xs-8 col-sm-6">
          <% &#9889; rating %>
        <%#/div>
        <%#div class="col-xs-4 col-sm-6"%>
        <center><%= link_to "Visit", @random_seller2, class: 'white-text' %></center>
        <%#/div%>
      </div>                  
    </div>
  <% end %>
</div>

app/views/sellers/_random_seller_mobile.html.erb
<div class="sub-title">SELLERS OF <%= @material.name.upcase %></div>
<br />
<div class="col-xs-6">
  <div class="thumbnail">
    <% if @random_seller.logo? %>
      <%= link_to (image_tag @random_seller.logo.url(:sidebar)), seller_path(@random_seller), class: 'seller-preview' %>
    <% else %>
      <%= link_to (image_tag '/thumbnail-sidebar.png'), seller_path(@random_seller), class: 'seller-preview' %>
    <% end %>

    <div class="caption">
      <h4 style="font-size:16px;"><%= link_to @random_seller2.name, seller_path(@random_seller2) %></h4>
      <div style="font-size:12px;"><%= @random_seller2.country %></div>
    </div>
    <div class="panel-footer">
      <div class="row">
      <%#div class="col-xs-8 col-sm-6">
        <% &#9889; rating %>
      <%#/div>
      <%#div class="col-xs-4 col-sm-6"%>
      <center><%= link_to "Visit", @random_seller, class: 'white-text' %></center>
      <%#/div%>
      </div>                  
    </div>
  </div>
</div>
<div class="col-xs-6">
  <div class="thumbnail">
  <% if @random_seller2.logo? %>
    <%= link_to (image_tag @random_seller2.logo.url(:sidebar)), seller_path(@random_seller2), class: 'seller-preview' %>
  <% else %>
      <%= link_to (image_tag '/thumbnail-sidebar.png'), seller_path(@random_seller2), class: 'seller-preview' %>
  <% end %>
    <div class="caption">
      <h4 style="font-size:16px;"><%= link_to @random_seller2.name, seller_path(@random_seller2) %></h4>
      <div style="font-size:12px;"><%= @random_seller2.country %></div>
    </div>
    <div class="panel-footer">
      <div class="row">
      <%#div class="col-xs-8 col-sm-6">
        <% &#9889; rating %>
      <%#/div>
      <%#div class="col-xs-4 col-sm-6"%>
      <center><%= link_to "Visit", @random_seller2, class: 'white-text' %></center>
      <%#/div%>
      </div>                  
    </div>
  </div>
</div>

app/views/sellers/edit.html.erb
<div class="container" id="seller-form">
  <div class="image"></div>
  <div class="frm"><br />
      <div class="sub-title">STORE SETTINGS</div><br />
        <%= form_for @seller, html: { multipart: true } do |form| %>
          <% if @seller.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

              <ul>
              <% seller.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.text_field :name, placeholder: "Name", class: 'form-control', :required => true %>
          </div>

          <br />

          <div class="field">
            <%= form.text_area :description, placeholder: "Description (max 370 characters)", :maxlength => 370, class: 'form-control sell' %>
          </div>
          <br />

          <div class="field">
            <%= form.label :country_of_your_production_facility %>
            <%= form.country_select :country, priority_countries: ["US", "GB", "DE", "CN", "JP"], placeholder: "Country", class: 'form-control' %>
          </div>

          <br />

          <div class="input-group">
            <span class="input-group-addon" id="basic-addon3" aria-describedby="basic-addon3">Include "https://"</span>
            <%= form.text_field :website, placeholder: "https://yourwebsite.com", class: 'form-control' %>
          </div>

          <br />

          <div class="field">
            <%= form.text_field :email, placeholder: "Email", class: 'form-control'  %>
          </div>

          <br />

          <div class="input-group">
            <%= form.label :logo_300x300px %><br />
            <%= form.file_field :logo %>
            <%= form.hidden_field :logo_cache %>
          </div>

          <br />

          <div class="actions">
            <%= form.submit "Update settings", class: 'btn btn-primary' %>
          </div>
          <br />
          <%= link_to 'Delete seller', seller_path(@seller),
            data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger' %>
        <% end %>
      </form>
  </div>
</div>

app/views/sellers/index.html.erb
<br />
<% @sellers.each do |seller| %>
    <div class="col-md-3 col-sm-4">
      <div class="thumbnail">
        <% if seller.logo? %>
          <%= link_to (image_tag seller.logo.url(:small)), seller, class: 'seller-preview' %>
        <% else %>
          <%= link_to (image_tag '/thumbnail.png'), seller, class: 'seller-preview' %>
        <% end %>
        <div class="caption">
          <h4 style="font-size:16px;"><%= link_to seller.name.truncate(20), seller %></h4>
          <div style="font-size:12px;"><%= seller.country %></div>
        </div>
        <div class="panel-footer">
          <div class="row">
            <%#div class="col-xs-8 col-sm-6">
              <% &#9889; rating %>
            <%#/div>
            <%#div class="col-xs-4 col-sm-6"%>
              <center><%= link_to "Visit", seller, class: 'white-text' %></center>
            <%#/div%>
          </div>                  
        </div>
      </div>
    </div>
<% end %>
<div class="paginate-parent">
    <div class="paginate">
        <%= paginate @sellers %>
    </div>
</div>

app/views/sellers/new.html.erb
<%= render 'form', seller: @seller %>

app/views/sellers/show.html.erb
<div class="row">
  <div class="col-xs-6 col-md-3 hide-mobile">
    <%= render 'sellers/random_seller' %>
  </div>
  <div class="col-md-9 nano-card">
    <%# SELLER PROFILE DESKTOP & TABLET %>
    <div class="seller-hide-mobile">
      <div class="col-xs-6 col-md-6">
        <h1><strong><%= @seller.name.upcase %></strong></h1>
        <% if current_user == @seller %>
        <%= link_to 'new product', new_product_path %>
        <% end %>
        <div class="country">
          <% if @seller.country? %><%= @seller.country%><% end %>
        </div>
        <% if @seller.website? %><%= link_to "Website", @seller.website, class: 'sub-title', target: :_blank %><% end %>
        <br />
        <div class="description-text">
          <% if @seller.description? %>
            <%= simple_format @seller.description %>
          <% end %>
        </div>
        <br />
        <%#<% if @seller.material_id? %><%#= link_to @seller.material.name, @seller.material, class: 'sub-title' %><%# end %>
      </div>

      <div class="col-xs-6 col-md-6">
        <% if @seller.logo? %>
          <%= image_tag @seller.logo.url(:small), class: 'img-responsive' %>
        <% else %>
          <%= image_tag '/thumbnail.png', class: 'img-responsive' %>
        <% end %>
      </div>
    </div>
    <%# END OF SELLER PROFILE DESKTOP & TABLET %>

    <%# SELLER PROFILE MOBILE %>
    <div class="seller-only-mobile">
      <h1><strong><%= @seller.name.upcase %></strong></h1>
      <div class="country">
        <% if @seller.country? %><%= @seller.country%><% end %>
      </div>
      <% if @seller.website? %><%= link_to "Website", @seller.website, class: 'sub-title', target: :_blank %><% end %>
      <br />
      <div class="description-text">
        <% if @seller.description? %>
          <%= @seller.description %>
        <% end %>
      </div>
      <br />
      <%#<% if @seller.material_id? %><%#= link_to @seller.material.name, @seller.material, class: 'sub-title' %><%# end %>

      <center>
        <% if @seller.logo? %>
          <%= image_tag @seller.logo.url(:small), class: 'img-responsive' %>
        <% else %>
          <%= image_tag '/thumbnail.png', class: 'img-responsive' %>
        <% end %>
      </center>
    </div>
    <%# END OF SELLER PROFILE MOBILE %>
  <hr>
  </div>
  <div class="col-md-9 nano-card">
    <%# SELLER PROFILE DESKTOP & TABLET %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Product</th>
          <th>Material</th>
          <th>Price</th>
        </tr>
      </thead>

      <tbody>
      <div class="sub-title"><%= @seller.name.upcase %> PRODUCTS</div>
        <% @products.limit(10).each do |product| %>
          <tr>
          <td><%= link_to product.name, product_path(product) %></td>
          <td><%= link_to product.material.name, product.material %></td>
          <td><%= product.price if product.price %></td>
        <% end %>
          </tr>
      </tbody>
    </table>
      <div class="paginate-parent">
          <div class="paginate">
              <%= paginate @products %>
          </div>
      </div>

  </div>
<div class="row">

  <div class="col-xs-6 col-md-3">

    </div>
    <div class="col-xs-12 col-md-8">
      <br />
      <br />

      <div class="sub-title">OTHER SELLERS</div>
      <br />      

      <% @sellers.each do |seller| %>
        <div class="col-sm-4 col-md-4">
          <div class="thumbnail">
            <% if seller.logo? %>
              <%= link_to (image_tag seller.logo.url(:small)), seller, class: 'seller-preview' %>
            <% else %>
              <%= link_to (image_tag '/thumbnail.png'), seller, class: 'seller-preview' %>
            <% end %>
            <div class="caption">
              <h4 style="font-size:16px;"><%= link_to seller.name, seller %></h4>
              <div style="font-size:12px;"><%= link_to seller.country, seller %></div>
            </div>
            <div class="panel-footer">
              <div class="row">
                <%#div class="col-xs-8 col-sm-6">
                  <% &#9889; rating %>
                <%#/div>
                <%#div class="col-xs-4 col-sm-6"%>
                <center><%= link_to "Visit", @random_seller, class: 'white-text' %></center>
                <%#/div%>
              </div>                  
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>