config/routes.rb
Rails.application.routes.draw do
  resources :bots do
    collection { post :how }
  end
  resources :bot_users
  resources :pdfs
  resources :pages
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :sellers
  resources :materials
  root 'pages#about'
  resources :products
  get "products/:seller/:id", to: 'products#show', as: 'show_product'
  namespace 'api' do
    namespace 'v1' do
      resources :bot_users
  	end
  end

  get 'pages/about', to: 'pages#about'
  get 'pages/how', to: 'pages#how'

  get 'callback/index'
  post '/' => 'callback#received_data'
  get 'callback/received_data'
end

app/models/bot_user.rb
class BotUser < ApplicationRecord
	alias_attribute :test_test, :'test test'
	alias_attribute :last_name, :'last name'
	alias_attribute :messenger_user_id, :'messenger user id'
	alias_attribute :chatfuel_user_id, :'chatfuel user id'
	alias_attribute :first_name, :'first name'
	alias_attribute :last_user_freeform_input, :'last user freeform input'
	alias_attribute :pofile_pic_url, :'profile pic url'
  paginates_per 20
  belongs_to :user, optional: true
  belongs_to :bot, optional: true
  belongs_to :page, optional: true
end

app/controllers/api/v1/bot_users_controller.rb
module Api
  module V1
    class BotUsersController < ApplicationController
      rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
      protect_from_forgery with: :null_session
      skip_before_action :verify_authenticity_token

      def index
        bot_users = BotUser.bot_user('created_at DESC');
        render json: {status: 'SUCCESS', message:'Loaded bot_user', data:bot_users},status: :ok
      end

      def show
        bot_user = BotUser.find(params[:id])
        render json: {status: 'SUCCESS', message:'Loaded bot_user', data:bot_user},status: :ok
      end

      def create
        bot_user = BotUser.new(bot_user_params)
        if bot_user.save
          render json: {status: 'SUCCESS', message:'Saved bot_user', data:bot_user },status: :ok
        else
          render json: {status: 'ERROR', message:'bot_user not saved',
          data:bot_user.errors},status: :unprocessable_entity
        end
      end

      def connect
        messenger_user_id = params['messenger user id']
        first_name = params['first name']
        last_name = params['last name']
        chatfuel_user_id = params['chatfuel user id']
        last_user_freeform_input = params['last user freeform input']
        profile_pic_url = params['profile pic url']
      end

      private

      def bot_user_params
        params.permit(:first_name, :messenger_user_id, :created_at_desc, :last_name, :'last name', :'test test', :'first name', :'messenger user id', :timezone, :gender, :locale, :chatfuel_user_id, :'chatfuel user id', :source, :last_user_freeform_input, :'last user freeform input', :profile_pic_url, :'profile pic url', :country, :bot_id, :user_id)
      end
    end
  end
end

app/controllers/bot_users_controller.rb
class BotUsersController < ApplicationController
  before_action :set_bot_user, only: [:show, :edit, :update, :destroy]

  # GET /bot_users
  # GET /bot_users.json
  def index
    @bot_users = BotUser.all.order('created_at DESC').page(params[:page])
  end

  # GET /bot_users/1
  # GET /bot_users/1.json
  def show
    @bot_user = BotUser.find(params[:id])
    @bot_user = current_user.bot_users.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        bot_user = BotUserPdf.new(@bot_users)
        send_data bot_user.render, filename: "pdf_#{@bot_user.first_name}.bot_user",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /bot_users/new
  def new
    @bot_user = BotUser.new
  end

  # GET /bot_users/1/edit
  def edit
  end

  # POST /bot_users
  # POST /bot_users.json
  def create
    @bot_user = BotUser.new(bot_user_params)

    respond_to do |format|
      if @bot_user.save
        format.html { redirect_to @bot_user, notice: 'Bot user was successfully created.' }
        format.json { render :show, status: :created, location: @bot_user }
      else
        format.html { render :new }
        format.json { render json: @bot_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bot_users/1
  # PATCH/PUT /bot_users/1.json
  def update
    respond_to do |format|
      if @bot_user.update(bot_user_params)
        format.html { redirect_to @bot_user, notice: 'Bot user was successfully updated.' }
        format.json { render :show, status: :ok, location: @bot_user }
      else
        format.html { render :edit }
        format.json { render json: @bot_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bot_users/1
  # DELETE /bot_users/1.json
  def destroy
    @bot_user.destroy
    respond_to do |format|
      format.html { redirect_to bot_users_url, notice: 'Bot user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def connect
    messenger_user_id = params['messenger user id']
    first_name = params['first name']
    last_name = params['last name']
    chatfuel_user_id = params['chatfuel user id']
    last_user_freeform_input = params['last user freeform input']
    profile_pic_url = params['profile pic url']
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bot_user
    @bot_user = BotUser.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bot_user_params
    params.require(:bot_user).permit(:first_name, :messenger_user_id, :created_at_desc, :last_name, :'last name', :'test test', :'first name', :'messenger user id', :timezone, :gender, :locale, :chatfuel_user_id, :'chatfuel user id', :source, :last_user_freeform_input, :'last user freeform input', :profile_pic_url, :'profile pic url', :country, :bot_id, :user_id, :city)
  end


end

app/helpers/bot_users_helper.rb
module BotUsersHelper
end

app/views/bot_users/_form.html.erb
<%= form_with(model: bot_user, local: true) do |form| %>
  <% if bot_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bot_user.errors.count, "error") %> prohibited this bot_user from being saved:</h2>

      <ul>
      <% bot_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :bot_id %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :bot_id, :value => current_user.bot.secret_code %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :'first name' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :'last name' %>
  </div>

  <div class="field">
    <%= form.label :messenger_user_id %>
    <%= form.number_field :'messenger user id' %>
  </div>

  <div class="field">
    <%= form.label :chatfuel_user_id %>
    <%= form.number_field :'chatfuel user id' %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.country_select :country %>
  </div>


  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :'gender' %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :'source' %>
  </div>

  <div class="field">
    <%= form.label :timezone %>
    <%= form.text_field :'timezone' %>
  </div>

  <div class="field">
    <%= form.label :locale %>
    <%= form.text_field :'locale' %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bot_users/edit.html.erb
<h1>Editing Bot User</h1>

<%= render 'form', bot_user: @bot_user %>

<%= link_to 'Show', @bot_user %> |
<%= link_to 'Back', bot_users_path %>

app/views/bot_users/index.html.erb
<% if user_signed_in? %>
  <%= line_chart BotUser.group_by_day(:created_at).count %>

  Gender chart:
  <%= pie_chart BotUser.group(:gender).count %>



  <%= geo_chart BotUser.group(:country).count %>

  <%= geo_chart BotUser.group(:locale).count %>


  <div class="nano-card">
      <table class="table table-hover">
          <thead>
          <tr>
            <th>ID</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Messenger User ID</th>
            <th>Gender</th>
            <th>Timezone</th>
            <th>Source</th>
            <th>City</th>
            <th>Country</th>
            <th>Last user freeform input</th>
          </tr>
          </thead>
          <tbody>
          <% bot_users.each do |bot_user| %>
              <tr>
                <td><%= link_to current_userbot_user.id, bot_user_path(bot_user) %></td>
                <td><%= link_to bot_user.first_name, bot_user_path(bot_user)  %></td>
                <td><%= bot_user.last_name %></td>
                <td><%= bot_user.messenger_user_id %></td>
                <td><%= bot_user.gender %></td>
                <td><%= bot_user.timezone %></td>
                <td><%= bot_user.source %></td>
                <td><%= bot_user.city %></td>
                <td><%= bot_user.country %></td>
                <td><%= bot_user.last_user_freeform_input if bot_user.last_user_freeform_input  %></td>
              </tr>
          <% end %>
          </tbody>
      </table>
      <div class="paginate-parent">
          <div class="paginate">
              <%= paginate @bot_users %>
          </div>
      </div>
  </div>
<% end %>

app/views/bot_users/new.html.erb
<h1>New Bot User</h1>

<%= render 'form', bot_user: @bot_user %>

<%= link_to 'Back', bot_users_path %>

app/views/bot_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @bot_user.first_name %>
</p>
<p>
  <strong>Last name:</strong>
  <%= @bot_user.last_name %>
</p>
<p>
  <strong>Messenger User ID:</strong>
  <%= @bot_user.messenger_user_id %>
</p>
<p>
  <strong>Country:</strong>
  <%= @bot_user.country %>
</p>


<%= link_to 'Edit', edit_bot_user_path(@bot_user) %> |
<%= link_to 'Back', bot_users_path %>