config/routes.rb
Rails.application.routes.draw do
  resources :bots do
    collection { post :how }
  end
  resources :bot_users
  resources :pdfs
  resources :pages
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :sellers
  resources :materials
  root 'pages#about'
  resources :products
  get "products/:seller/:id", to: 'products#show', as: 'show_product'
  namespace 'api' do
    namespace 'v1' do
      resources :bot_users
  	end
  end

  get 'pages/about', to: 'pages#about'
  get 'pages/how', to: 'pages#how'

  get 'callback/index'
  post '/' => 'callback#received_data'
  get 'callback/received_data'
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-warning alert-dismissable">
	<button class="close" data-dismiss="alert">
		<i class="glyphicon glyphicon-remove-circle"></i>
	</button>
		<%= content_tag(:div, msg) %>
	</div>
<% end %>

app/views/home/_footer.html.erb
<div class="footer">
    <div id="footer">
      <div class="container">
        <p class="text-muted credit text-center">
        	<br/>Made by <a href="http:/jonaspreisler.com" target="_blank" style="color:#a9a9a9;background:#1c1c1c;border-radius:5px;padding-left:5px;padding-right:5px;"> Jonas</a>   |  hej@jonaspreisler.com
        	<br />
        	2018 &copy Tekuila
        </p>
      </div>
    </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag ('/logo.png'), class: 'logo smaller-image-mobile' %>
      <% end %>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%= link_to "Bots", bots_path, class: 'nano-nav' %>
        <%= link_to "About", root_path, class: 'nano-nav' %>
        <% if user_signed_in? %>
          <div class="dropdown div-inline">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              &#9776;
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "How?", pages_how_path %></li>
              <li><%= link_to "Add bot", new_bot_path, class: 'nano-nav' %></li>
              <li><%= link_to 'Account settings', edit_user_registration_path, class: 'nano-nav' %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nano-nav'  %></li>
            </ul>
          </div>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'nano-nav' %>
          <% end %>                        


      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<%= @coins %>
<% if @symbol %>
	<% for x in @coin %>
		<% if @symbol == x["symbol"] %>
			<%= x["name"] %>: $<%= x["price_usd"] %><br />
			Rank: <%= x["rank"] %><br /><br />
		<% end %>
	<% end %>
<% end %>

app/views/home/lookup.html.erb
<h3>Currency Lookup</h3>
<br />
<%= form_tag home_lookup_path, :method => 'POST' do %>
	<%= text_field_tag 'sym', nil, placeholder: 'Enter crypto symbol', size: 50 %>
	<%= submit_tag 'Lookup Quotes' %>
<% end %> 
<br />

<%= @symbol %>

<% if @symbol %>
	<% for x in @lookup_coin %>
		<% if @symbol == x["symbol"] %>
			<%= x["name"] %>: $<%= x["price_usd"] %><br />
			Rank: <%= x["rank"] %><br /><br />
		<% end %>
	<% end %>
<% end %>