config/routes.rb
Rails.application.routes.draw do
  resources :bots do
    collection { post :how }
  end
  resources :bot_users
  resources :pdfs
  resources :pages
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :sellers
  resources :materials
  root 'pages#about'
  resources :products
  get "products/:seller/:id", to: 'products#show', as: 'show_product'
  namespace 'api' do
    namespace 'v1' do
      resources :bot_users
  	end
  end

  get 'pages/about', to: 'pages#about'
  get 'pages/how', to: 'pages#how'

  get 'callback/index'
  post '/' => 'callback#received_data'
  get 'callback/received_data'
end

app/models/pdf.rb
class Pdf < ApplicationRecord
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: [:show, :edit, :update, :destroy]

  # GET /pdfs
  # GET /pdfs.json
  def index
    @pdfs = Pdf.all
  end

  # GET /pdfs/1
  # GET /pdfs/1.json
  def show
    @pdf = Pdf.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = AnalyticsPdf.new(@pdf)
        send_data pdf.render, filename: "pdf_#{@pdf.business_name}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
    @bot_user = Bot_user.all
  end

  # GET /pdfs/new
  def new
    @pdf = Pdf.new
  end

  # GET /pdfs/1/edit
  def edit
  end

  # POST /pdfs
  # POST /pdfs.json
  def create
    @pdf = Pdf.new(pdf_params)

    respond_to do |format|
      if @pdf.save
        format.html { redirect_to @pdf, notice: 'Pdf was successfully created.' }
        format.json { render :show, status: :created, location: @pdf }
      else
        format.html { render :new }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdfs/1
  # PATCH/PUT /pdfs/1.json
  def update
    respond_to do |format|
      if @pdf.update(pdf_params)
        format.html { redirect_to @pdf, notice: 'Pdf was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdf }
      else
        format.html { render :edit }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfs/1
  # DELETE /pdfs/1.json
  def destroy
    @pdf.destroy
    respond_to do |format|
      format.html { redirect_to pdfs_url, notice: 'Pdf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf
      @pdf = Pdf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pdf_params
      params.require(:pdf).permit(:amount_of_users, :business_name, :date)
    end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/pdfs/_form.html.erb
<%= form_with(model: pdf, local: true) do |form| %>
  <% if pdf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pdf.errors.count, "error") %> prohibited this pdf from being saved:</h2>

      <ul>
      <% pdf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount_of_users %>
    <%= form.number_field :amount_of_users %>
  </div>

  <div class="field">
    <%= form.label :business_name %>
    <%= form.text_field :business_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pdfs/edit.html.erb
<h1>Editing Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Show', @pdf %> |
<%= link_to 'Back', pdfs_path %>

app/views/pdfs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pdfs</h1>

<table>
  <thead>
    <tr>
      <th>Amount of users</th>
      <th>Business name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pdfs.each do |pdf| %>
      <tr>
        <td><%= pdf.amount_of_users %></td>
        <td><%= pdf.business_name %></td>
        <td><%= pdf.date %></td>
        <td><%= link_to 'Show', pdf %></td>
        <td><%= link_to 'Edit', edit_pdf_path(pdf) %></td>
        <td><%= link_to 'Destroy', pdf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pdf', new_pdf_path %>

app/views/pdfs/new.html.erb
<h1>New Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Back', pdfs_path %>

app/views/pdfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount of users:</strong>
  <%= @pdf.amount_of_users %>
</p>

<%= line_chart Bot_user.group_by_day(:created_at).count %>

<p>
  <strong>Business name:</strong>
  <%= @pdf.business_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @pdf.date %>
</p>

<%= link_to "Download PDF", pdf_path(@pdf), format: "pdf", class: 'btn btn-primary' %>

<%= link_to 'Edit', edit_pdf_path(@pdf) %> |
<%= link_to 'Back', pdfs_path %>